In [1]:
#Boolean masks

In [2]:
import numpy as np

In [3]:
x = np.array([1, 2, 3, 4, 5])

In [4]:
x < 3

array([ True,  True, False, False, False], dtype=bool)

In [5]:
x == 3

array([False, False,  True, False, False], dtype=bool)

In [6]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False], dtype=bool)

In [7]:
np.count_nonzero(x < 3) #this effectively counts the Trues

2

In [11]:
np.sum(x < 3) #this effectively does the same thingg

2

In [15]:
rng = np.random.RandomState(0)

In [16]:
y = rng.randint(10, size=(3,4))

In [17]:
y

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [21]:
np.all(y < 8, axis = 1) #this tests rows

array([ True, False,  True], dtype=bool)

In [20]:
np.all(y < 6, axis = 0) #this tests columns

array([False, False, False, False], dtype=bool)

In [28]:
y [y < 5] #this indexes on a condition rather than a position, and just returns back the values that satisfy the condition

array([0, 3, 3, 3, 2, 4])

In [29]:
y < 5 #that is the mask that is being applied

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]], dtype=bool)